/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graaadle;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void finalTest() throws IOException {
        assertTrue(TestClass.setPort("localhost",4513));
        assertEquals(TestClass.sendMsg("hello"),"hello");
        assertEquals(TestClass.replyMsg("ACC"),"ACC");
    }

}
